services:
  service1:
    profiles:
      - dev
    image: service1-dev
    ports:
      - "8080:3000"
    restart: unless-stopped
    build:
      context: service1/
      dockerfile: Dockerfile
    container_name: aos-service1
    env_file:
      - "service1/.env.Dev"
    networks:
      - aos-network

  service2:
    profiles:
      - dev
    image: service2-dev
    ports:
      - "8081:3000"
    restart: unless-stopped
    build:
      context: service2/
      dockerfile: Dockerfile
    container_name: aos-service2
    env_file:
      - "service2/.env.Dev"
    networks:
      - aos-network


networks:
  aos-network:
    driver: bridge
