services:
  service1:
    profiles:
      - dev
      - dev2
    image: service1-dev
    environment:
      DB_HOST: postgres-db2     # <— IMPORTANT
      DB_PORT: 5432              # <— internal container port
      DB_USER: admin  
      DB_PASS: admin123
      DB_NAME: bank
      RABBITMQ_URL: "amqp://kalo:kalo@rabbitmq:5672"
    ports:
      - "8080:3000"
    restart: unless-stopped
    build:
      context: service1/
      dockerfile: Dockerfile
    container_name: aos-service1
    env_file:
      - "service1/.env.Dev"
    networks:
      - aos-network

  service2:
    profiles:
      - dev
    image: service2-dev
    environment:
      DB_HOST: postgres-db2  
      DB_PORT: 5432             
      DB_USER: admin  
      DB_PASS: admin123
      DB_NAME: bank
      RABBITMQ_URL: "amqp://kalo:kalo@rabbitmq:5672"
    ports:
      - "8081:3000"
    restart: unless-stopped
    build:
      context: service2/
      dockerfile: Dockerfile
    container_name: aos-service2
    env_file:
      - "service2/.env.Dev"
    networks:
      - aos-network

  db1:
    profiles:
      - dev
      - db1
      - dev2
    container_name: postgres-db1
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres
      POSTGRES_DB: bank
    # volumes:
    #   - db1:/data/postgres
    ports:
      - "5331:5432"
    networks:
      - aos-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db2:
    container_name: postgres-db2
    image: postgres:latest
    profiles:
      - dev
      - db2
      - dev2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres
      POSTGRES_DB: bank
    # volumes:
    #   - db2:/data/postgres
    ports:
      - "5333:5432"
    networks:
      - aos-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:latest
    profiles:
      - dev
      - db1
      - dev2
    container_name: rabbitmq
    networks:
      - aos-network
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: kalo
      RABBITMQ_DEFAULT_PASS: kalo
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]." 

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

networks:
  aos-network:
    driver: bridge
