services:
  service1:
    profiles:
      - dev
    image: service1-dev
    ports:
      - "8080:3000"
    restart: unless-stopped
    build:
      context: service1/
      dockerfile: Dockerfile
    container_name: aos-service1
    env_file:
      - "service1/.env.Dev"
    networks:
      - aos-network

  service2:
    profiles:
      - dev
    image: service2-dev
    ports:
      - "8081:3000"
    restart: unless-stopped
    build:
      context: service2/
      dockerfile: Dockerfile
    container_name: aos-service2
    env_file:
      - "service2/.env.Dev"
    networks:
      - aos-network

  db1:
    profiles:
      - dev
      - db1
    container_name: postgres-db1
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres
      POSTGRES_DB: bank
    # volumes:
    #   - db1:/data/postgres
    ports:
      - "5331:5432"
    networks:
      - aos-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db2:
    container_name: postgres-db2
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres
      POSTGRES_DB: bank
    # volumes:
    #   - db2:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - aos-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  aos-network:
    driver: bridge
