apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db1
  template:
    metadata:
      labels:
        app: postgres-db1
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin123"
            - name: POSTGRES_DB
              value: "bank"
            - name: PGDATA
              value: "/data/postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db1-data
              mountPath: /data/postgres
      volumes:
        - name: db1-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db1
spec:
  type: ClusterIP
  selector:
    app: postgres-db1
  ports:
    - port: 5432
      targetPort: 5432
