apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: service1-dev
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "postgres-db1"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "admin123"
            - name: DB_NAME
              value: "bank"
            - name: RABBITMQ_URL
              value: "amqp://kalo:kalo@rabbitmq:5672"
            # If you need anything from service1/.env.Dev,
            # add extra env vars here manually.
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080   # maps to 8080 in docker-compose-ish